### PR TITLE
First cut at changes this to 2.0 API.

### PR DESCRIPTION
**Pull request by phil-levis**
I am not 100% sure on the Rust code. 

Also needs the book to be regenerated -- this is only the markdown.

### CODE REVIEW

**Review by ppannuto — APPROVED** [review]
Some of the whitespace, particularly in the later code examples, looks a little funny, but all of the substantive content looks correct.

**Review by bradjc — APPROVED** [review]

**Comment by phil-levis** [comment]
> 
> 
> Some of the whitespace, particularly in the later code examples, looks a little funny, but all of the substantive content looks correct.

Will fix.

**Comment by hudson-ayers** [comment]
No bors in this repo :)

**Pull request merged**
