### PR TITLE
remove built version from repo

### LINKED ISSUE #9: We shouldn't have .html in this repo
Looking at diffs is murderous because most is built output. We should have netlify run the build step as part of the deploy operation (like we do in tock proper) and remove all of the built artifacts from this repo

### PR DESCRIPTION
**Pull request by ppannuto**
This PR moves the built html out of this repo by having netlify build and deploy the book.

One consequence of doing this easily was pinning the `mdbook` version that we use to ensure local and remote builds are consistent, but that's probably a good thing to have been doing anyway.

Seems to work fine: https://6039701a197dff3d44a3c31b--frosty-brattain-7cc102.netlify.app/

The last piece will be changing over the domain from github pages to netlify.

Fixes #9.

### CODE REVIEW

**Comment by hudson-ayers** [comment]
When I click that netlify link I get:
```
Not found - Request ID: 2e119561-d051-45eb-ad0c-5f4396ce91a1-2951157
```

**Comment by ppannuto** [comment]
Ah, I pushed an updated patch, netlify must purge builds from older commits. Try https://deploy-preview-14--stupefied-colden-0f32a7.netlify.app/

**Comment by bradjc** [comment]
Do we need @amit to do the switchover? I want to merge but I don't want the book to disappear in the meantime.

**Review by hudson-ayers — APPROVED** [review]

**Comment by alevy** [comment]
Why would we need me to do any switchover? The site is already hosted on Netlify (I believe, actually, in @ppannuto's organization), so no changes to DNS or anything necessary. This just builds it on Netlify as opposed to relying on the HTML already being there, right?

**Review by alevy — APPROVED** [review]

**Review by bradjc — APPROVED** [review]

**Comment by bradjc** [comment]
Ok let's try it.

**Pull request merged**
