### PR TITLE
Fix virtualizers typos and add an image

### PR DESCRIPTION
**Pull request by kevtan**
I fixed some typos in the virtualizers doc and added a helpful image to show the overall architecture of a virtualization scheme.

### CODE REVIEW

**Review by hudson-ayers — APPROVED** [review]
Love the image, thanks! In order for the changes to show up in the actual book, you need to run `mdbook build` from the root of the repo and push the modified HTML files to this PR before it is merged.

**Comment by kevtan** [comment]
@hudson-ayers Got it. Thanks for the heads up!

**Review by hudson-ayers — APPROVED** [review]
Looks good, I would merge but I don't have commit access to this repo

**Comment by hudson-ayers** [comment]
I stand corrected

**Pull request merged**
